services:
- autoDeploy: true
  buildCommand: pip install --upgrade pip && pip install -r requirements_render_enhanced.txt
    --no-cache-dir
  env: python
  envVars:
  - key: PYTHON_VERSION
    value: 3.11.0
  - key: STREAMLIT_SERVER_HEADLESS
    value: 'true'
  - key: STREAMLIT_SERVER_ADDRESS
    value: 0.0.0.0
  - key: STREAMLIT_SERVER_ENABLE_CORS
    value: 'false'
  - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
    value: 'false'
  - key: STREAMLIT_SERVER_FILE_WATCHER_TYPE
    value: none
  - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: 'false'
  - key: STREAMLIT_SERVER_RUN_ON_SAVE
    value: 'false'
  - key: CACHE_TTL
    value: '300'
  - key: MAX_CACHE_SIZE
    value: '200'
  - key: DB_PATH
    value: predictions.db
  - key: LOG_LEVEL
    value: INFO
  healthCheckPath: /
  name: financial-analyzer-pro-enhanced
  plan: free
  region: oregon
  startCommand: streamlit run app_render_enhanced.py --server.port $PORT --server.address
    0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection
    false --server.fileWatcherType none
  type: web
