services:
  - type: web
    name: financial-analyzer-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements_render_safe.txt --no-cache-dir
    startCommand: streamlit run app_phase5_complete_integrated.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: false
      - key: STREAMLIT_SERVER_FILE_WATCHER_TYPE
        value: none
